### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by edescourtis** [welbornprod/pyvalbot#2]
Could you please add a license I would like to use this code but can't at the moment.

http://choosealicense.com/

MIT or LGPL would be nice

**Comment by cjwelborn** [comment]
Were you planning on using it in proprietary software?

**Comment by edescourtis** [comment]
Yes I was interested in reusing the sand-boxing code.

**Comment by cjwelborn** [comment]
After consideration I have switched to MIT. Pypy uses the MIT license for all of it's stuff (unless otherwise noted). Thanks for bringing this to my attention.
